return {
    ["Build"] = {
        Name = "Build",
        Description = "Build Blocks!",
        ToolType = "Utility",
        Image = "rbxassetid://70849764808733",
        SpawnWith = true,
    },
    ["Destroy"] = {
        Name = "Destroy",
        Description = "Destroy blocks!",
        ToolType = "Utility",
        Image = "rbxassetid://104333649397085",
        SpawnWith = true,
    },
}
